<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="arm" params="prefix color x_offset y_offset z_offset">
    
    <link name="${prefix}_arm_base">
      <visual>
        <geometry>
          <cylinder radius="0.04" length="0.05"/>
        </geometry>
        <material name="${color}"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="0.04" length="0.05"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.2"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    </link>

    <joint name="${prefix}_base_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_arm_base"/>
      <origin xyz="${x_offset} ${y_offset} ${z_offset}" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}_link1">
      <visual>
        <origin xyz="0 0 0.15" rpy="0 0 0"/>
        <geometry>
          <box size="0.04 0.04 0.3"/>
        </geometry>
        <material name="${color}"/>
      </visual>
      <collision>
        <origin xyz="0 0 0.15" rpy="0 0 0"/>
        <geometry>
          <box size="0.04 0.04 0.3"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0.15" rpy="0 0 0"/>
        <mass value="0.3"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    </link>

    <joint name="${prefix}_joint1" type="revolute">
      <parent link="${prefix}_arm_base"/>
      <child link="${prefix}_link1"/>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
    </joint>

    <link name="${prefix}_hand">
      <visual>
        <geometry>
          <sphere radius="0.05"/>
        </geometry>
        <material name="red"/>
      </visual>
      <collision>
        <geometry>
          <sphere radius="0.05"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
      </inertial>
    </link>
    
    <!-- Weight Sensor (Virtual Frame) -->
    <link name="${prefix}_weight_sensor"/>

    <joint name="${prefix}_hand_joint" type="fixed">
      <parent link="${prefix}_link1"/>
      <child link="${prefix}_hand"/>
      <origin xyz="0 0 0.3" rpy="0 0 0"/>
    </joint>

    <joint name="${prefix}_weight_sensor_joint" type="fixed">
      <parent link="${prefix}_hand"/>
      <child link="${prefix}_weight_sensor"/>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
    </joint>

  </xacro:macro>

  <xacro:arm prefix="left" color="grey" x_offset="${chassis_length/2 - 0.05}" y_offset="0.12" z_offset="${chassis_height/2 + 0.025}"/>
  <xacro:arm prefix="right" color="grey" x_offset="${chassis_length/2 - 0.05}" y_offset="-0.12" z_offset="${chassis_height/2 + 0.025}"/>

</robot>
